app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .auth.routes import auth
from .api.routes import api
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)

root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Quarterback, qb_schema, qbs_schema
# import uuid

api = Blueprint('api', __name__, url_prefix="/api")

@api.route('/quarterbacks', methods = ['POST'])
@token_required
def create_qb(current_user_token):
    team = request.json['team']
    user_token = current_user_token.token

    if not user_token:
        return jsonify({"error" : "Missing user token"}), 400

    try:
        if team in qb_info:
            div_conf_tpl, image_link = qb_info[team] 
            division, conference = div_conf_tpl   
        else:
            division = request.json['division']
            conference = request.json['conference']
            image_link = request.json['image_link']
    
    except KeyError:

        return jsonify({"error":"No team with that name found; check your spelling"}, "error")

    qb = Quarterback(team, division, conference, image_link, user_token=user_token)
    print(qb)

    db.session.add(qb)
    db.session.commit()

    response = qb_schema.dump(qb)
    return jsonify(response), 201

@api.route('/quarterbacks', methods = ['GET'])
@token_required
def get_qbs(current_user_token):
    a_user = current_user_token.token
    qbs = Quarterback.query.filter_by(user_token = a_user).all()
    response = qbs_schema.dump(qbs)
    return jsonify(response), 200

@api.route('/quarterbacks/<id>', methods = ['GET'])
@token_required
def get_single_qb(current_user_token, id):
    qb = Quarterback.query.get(id)
    response = qb_schema.dump(qb)
    return jsonify(response)

@api.route('/quarterbacks/<id>', methods = ['POST', 'PUT'])
@token_required
def update_qb(current_user_token, id):
    qb = Quarterback.query.get(id)
    qb.team = request.json["team"]
    qb.division = request.json["division"]
    qb.conference = request.json["conference"]
    qb.image_link = request.json["image_link"]
    qb.user_token = current_user_token.token

    db.session.commit()
    response = qb_schema.dump(qb)
    return jsonify(response), 200

@api.route('/quarterbacks/<id>', methods = ['DELETE'])
@token_required
def delete_qb(current_user_token, id):
    qb = Quarterback.query.get(id)

    db.session.delete(qb)
    db.session.commit()
    response = qb_schema.dump(qb)
    return jsonify(response)










qb_info = {
'bills': [('afc east', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723457/bills_zplcjn.png'],
'dolphins': [('afc east', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723459/dolphins_zb2b7t.png'],
'patriots': [('afc east', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/patriots_fsq94s.png'],
'jets': [('afc east', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/jets_a4bf2m.png'],
'ravens': [('afc north', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723455/ravens_es66tt.png'],
'bengals': [('afc north', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723457/bengals_o86yah.png'],
'browns': [('afc north', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723457/browns_qy2qtb.png'],
'steelers': [('afc north', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723455/steelers_ur8yws.png'],
'texans': [('afc south', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723455/texans_tbls1s.png'],
'colts': [('afc south', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723458/colts_bz0vpq.png'],
'jaguars': [('afc south', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/jaguars_em5o3b.png'],
'titans': [('afc south', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723455/titans_kp7tbf.png'],
'broncos': [('afc west', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723457/broncoos_nbtqmh.png'],
'chiefs': [('afc west', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723458/chiefs_ugmtys.png'],
'raiders': [('afc west', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/raiders_rmijha.png'],
'chargers': [('afc west', 'afc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723458/chargers_pf0kwn.png'],
'cowboys': [('nfc east', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723458/cowboys_ubcojz.png'],
'giants': [('nfc east', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/giants_hpyx2u.png'],
'eagles': [('nfc east', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723459/eagles_h5pipx.png'],
'commanders': [('nfc east', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723458/commanders_jolwjy.png'],
'bears': [('nfc north', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723457/bears_pgcmlt.png'],
'lions': [('nfc north', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/lions_ipc9so.png'],
'packers': [('nfc north', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/packers_xi2esb.png'],
'vikings': [('nfc north', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723456/vikings_vruadw.png'],
'falcons': [('nfc south', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723459/falcons_lccovf.png'],
'panthers': [('nfc south', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/panthers_f5hybg.png'],
'saints': [('nfc south', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723455/saints_wx7t1n.png'],
'buccaneers': [('nfc south', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723457/buccaneers_c6pw7g.png'],
'cardinals': [('nfc west', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723458/cardinals_kjksgt.png'],
'rams': [('nfc west', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723454/rams_lcuxo6.png'],
'49ers': [('nfc west', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723456/49ers_zmseuz.png'],
'seahawks': [('nfc west', 'nfc'), 'https://res.cloudinary.com/dkeozpkpv/image/upload/v1708723455/seahwaks_kuvr00.png']
}

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site',__name__,template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')


@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" type="text/css" href="../static/CSS/main.css">
<title></title>
</head>
<body>
    {% set is_profile_page = request.path == url_for('site.profile') %}
    <nav class="navbar navbar-expand-lg sticky-top navbar-custom-sz nav-border-custom {{ 'no-border' if current_user.is_authenticated and is_profile_page else '' }}">
        <div class="container">
            <a href="{{ url_for('site.home') }}" class="navbar-brand text-danger nav-link-bold nav-link-outline">Quarterback Selector</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse bg-custom" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link text-light nav-link-bold">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link text-light nav-link-bold">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link text-light nav-link-bold">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link text-light nav-link-bold">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link text-light nav-link-bold">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% block content %} {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html> 

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    {% if form_type == 'signup' %}
    <div class="form-group">
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control", placeholder="First Name") }}
            {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                    <div class="invalid-feedback" style="display:block;">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class="form-control", placeholder="Last Name") }}
            {% if form.last_name.errors %}
                {% for error in form.last_name.errors %}
                    <div class="invalid-feedback" style="display:block;">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </fieldset>
    </div>
    {% endif %}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class='form-control', placeholder='email@address.com') }}
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    <div class="invalid-feedback" style="display:block;">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder="Password here") }}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <div class="invalid-feedback" style="display:block;">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </fieldset>
    </div>
    <div class="form-group">
        {{ form.submit_button(class="btn btn-primary btn-block mt-2") }}
    </div>
</form>